### ISSUE TITLE
Support for PHP 5.4 traits

### ISSUE THREAD

**Issue by endel** [DEVSENSE/Phalanger#42]
Does Phalanger already supports traits?

I'm trying to build this simple example from [PHP documentation](http://php.net/manual/en/language.oop5.traits.php):

``` php
<?php
class Base {
    public function sayHello() {
        echo 'Hello ';
    }
}

trait SayWorld {
    public function sayHello() {
        parent::sayHello();
        echo 'World!';
    }
}

class MyHelloWorld extends Base {
    use SayWorld;
}

$o = new MyHelloWorld();
$o->sayHello();
```

Errors and stack trace using Visual Studio 2013 and [Phalanger 4.0](http://www.php-compiler.net/blog/2014/phalanger-4-0):

```
Error   1   The class 'SayWorld' has no parent  c:\users\endel\documents\visual studio 2013\Projects\PhalangerTraits\PhalangerTraits\index.php  10  10  PhalangerTraits
```

```
Error   2   Internal error! 
Please, report this bug via http://phalanger.codeplex.com/workitem/list/basic.
Additional information: 
The method or operation is not implemented.
   at PHP.Core.Compiler.AST.NodeCompilers.TraitsUseCompiler.Analyze(TraitsUse node, Analyzer analyzer)
   at PHP.Core.Compiler.AST.NodeCompilers.TypeMemberDeclCompiler`1.PHP.Core.Compiler.AST.ITypeMemberDeclCompiler.Analyze(TypeMemberDecl node, Analyzer analyzer)
   at PHP.Core.Compiler.AST.NodeCompilers.TypeDeclCompiler.Analyze(TypeDecl node, Analyzer analyzer)
   at PHP.Core.Compiler.AST.NodeCompilers.StatementCompiler`1.PHP.Core.Compiler.AST.IStatementCompiler.Analyze(Statement node, Analyzer analyzer)
   at PHP.Core.Compiler.AST.NodeCompilers.GlobalCodeCompiler.Analyze(GlobalCode ast, Analyzer analyzer)
   at PHP.Core.Analyzer.Analyze(CompilationSourceUnit sourceUnit)
   at PHP.Core.Reflection.ScriptCompilationUnit.AnalyzeRecursively(Analyzer analyzer)
   at PHP.Core.Reflection.InclusionGraphBuilder.AnalyzeDfsTree(PhpSourceFile rootSourceFile)
   at PHP.Core.Emit.ScriptAssemblyBuilder.CompileScripts(IEnumerable`1 sourceFiles, CompilationContext context)
   at PHP.Core.Emit.ScriptAssemblyBuilder.Build(IEnumerable`1 sourceFiles, CompilationContext context)
   at PHP.Core.ApplicationCompiler.Compile(ApplicationContext applicationContext, CompilerConfiguration config, ErrorSink errorSink, CompilationParameters ps)
        -1  0   PhalangerTraits
```

Since the error tells about "PhalangerTraits", I suppose it is implemented somehow, correct? Am I missing something here?

Thank you.

**Comment by jakubmisek** [comment]
The feature will be implemented in https://github.com/peachpiecompiler/peachpie
